/**
 * GENERATED by `npm run goldens:generate` — do not edit.
 *
 * Every value below was read from `migration/sheet-dump.json`'s `value`
 * field and converted to minor units by half-up rounding. Editing a number
 * here to make a test pass inverts the whole point of the file: the sheet is
 * the authority, and a failing golden means the port is wrong (FR-010).
 *
 * Source dump extracted at 2026-08-27T10:06:31.254Z.
 */

export const GOLDEN_TODAY = '2026-08-27'

/** `Rates!B2:B4`, at the scales R1 fixes per class. */
export const GOLDEN_RATES = {
  USD: { rateMinor: 502554, scale: 4, asOf: '2026-08-17' },
  GOLD: { rateMinor: 750000, scale: 2, asOf: '2026-08-17' },
  SILVER: { rateMinor: 10200, scale: 2, asOf: '2026-08-17' },
} as const

/** `Total!D2:L2` — the non-investment partition. */
export const GOLDEN_TOTAL = {
  usdNative: 244400,
  usdEgp: 12282420,
  goldNative: 0,
  goldEgp: 0,
  silverNative: 0,
  silverEgp: 0,
  egp: 6700000,
  shortTermLiabilities: 8010900,
  totalOfAll: 10971520,
} as const

/** `Investment!D2:K2` — the investment partition. */
export const GOLDEN_INVESTMENT = {
  usdNative: 3600,
  usdEgp: 180919,
  goldNative: 22500,
  silverNative: 750000,
  goldEgp: 16875000,
  silverEgp: 7650000,
  egp: 3300000,
  investmentTotal: 28005919,
} as const

/** `Net Worth!B12:B20`. Both net-worth figures, neither unqualified (D4). */
export const GOLDEN_NET_WORTH = {
  totalAssets: 46988339,
  shortTermLiabilities: 8010900,
  remainingInstallments: 821460520,
  totalLiabilities: 829471420,
  includingInstallments: -782483081,
  excludingInstallments: 38977439,
  liquid: 18982420,
} as const

/** `Installments!H2:H10`, evaluated by the sheet at 2026-08-27T10:06:31.254Z. */
export const GOLDEN_INSTALLMENTS = {
  totalScheduled: 919871100,
  totalPaid: 98410580,
  totalRemaining: 821460520,
  nextDueOn: '2026-09-15',
  nextAmountDue: 1475280,
  due3m: 24619580,
  due6m: 35499160,
  due12m: 109762220,
  overdue: 0,
} as const

/** `Dashboard!I2:I22` — 21 calendar-year buckets. */
export const GOLDEN_UNPAID_BY_YEAR = [
  {
    "year": 2025,
    "amountMinor": 0
  },
  {
    "year": 2026,
    "amountMinor": 26094860
  },
  {
    "year": 2027,
    "amountMinor": 153187980
  },
  {
    "year": 2028,
    "amountMinor": 74732180
  },
  {
    "year": 2029,
    "amountMinor": 135020000
  },
  {
    "year": 2030,
    "amountMinor": 64833500
  },
  {
    "year": 2031,
    "amountMinor": 66097500
  },
  {
    "year": 2032,
    "amountMinor": 65242500
  },
  {
    "year": 2033,
    "amountMinor": 62458000
  },
  {
    "year": 2034,
    "amountMinor": 62929000
  },
  {
    "year": 2035,
    "amountMinor": 64185000
  },
  {
    "year": 2036,
    "amountMinor": 46680000
  },
  {
    "year": 2037,
    "amountMinor": 0
  },
  {
    "year": 2038,
    "amountMinor": 0
  },
  {
    "year": 2039,
    "amountMinor": 0
  },
  {
    "year": 2040,
    "amountMinor": 0
  },
  {
    "year": 2041,
    "amountMinor": 0
  },
  {
    "year": 2042,
    "amountMinor": 0
  },
  {
    "year": 2043,
    "amountMinor": 0
  },
  {
    "year": 2044,
    "amountMinor": 0
  },
  {
    "year": 2045,
    "amountMinor": 0
  }
] as const

/** `Dashboard!F2:F6` — the combined position per class. */
export const GOLDEN_ASSET_MIX = [
  { sheetRef: 'Dashboard!F2', label: 'EGP cash & accounts', egpMinor: 10000000 },
  { sheetRef: 'Dashboard!F3', label: 'USD (in EGP)', egpMinor: 12463339 },
  { sheetRef: 'Dashboard!F4', label: 'Gold (in EGP)', egpMinor: 16875000 },
  { sheetRef: 'Dashboard!F5', label: 'Silver (in EGP)', egpMinor: 7650000 },
  { sheetRef: 'Dashboard!F6', label: 'Property (paid to date)', egpMinor: 0 },
] as const

/** `Transactions!G2` — 100 USD on 2026-08-24. */
export const GOLDEN_TRANSACTION_EGP = 502554

/** `Transactions!J2:N25` — the 24-month forward spine. */
export const GOLDEN_MONTHLY_ROLLUP = [
  {
    "month": "2026-08-01",
    "incomeMinor": 502554,
    "expenseMinor": 0,
    "netMinor": 502554,
    "savingsRate": 1
  },
  {
    "month": "2026-09-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2026-10-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2026-11-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2026-12-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2027-01-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2027-02-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2027-03-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2027-04-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2027-05-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2027-06-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2027-07-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2027-08-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2027-09-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2027-10-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2027-11-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2027-12-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2028-01-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2028-02-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2028-03-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2028-04-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2028-05-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2028-06-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  },
  {
    "month": "2028-07-01",
    "incomeMinor": 0,
    "expenseMinor": 0,
    "netMinor": 0,
    "savingsRate": null
  }
] as const

/** `History!A4:G4` — the sole genuine snapshot. Row 2 is a live mirror. */
export const GOLDEN_SNAPSHOT = {
  takenOn: '2026-08-17',
  liquidMinor: 29030000,
  investmentsMinor: 29030775,
  propertyPaidMinor: 0,
  shortTermLiabilitiesMinor: 35000000,
  remainingInstallmentsMinor: 579229100,
  netWorthExclInstallmentsMinor: 23060775,
} as const

/** `Total!I4:J10` — hand-typed short-term liabilities, one of them Arabic. */
export const GOLDEN_LIABILITIES = [
  {
    "sheetRef": "Total!I4",
    "name": "CC ADIB",
    "amountMinor": 0
  },
  {
    "sheetRef": "Total!I5",
    "name": "CC HSBC",
    "amountMinor": 0
  },
  {
    "sheetRef": "Total!I6",
    "name": "CASHBACK",
    "amountMinor": 1010900
  },
  {
    "sheetRef": "Total!I7",
    "name": "storia mine",
    "amountMinor": 0
  },
  {
    "sheetRef": "Total!I8",
    "name": "storia share",
    "amountMinor": 1000000
  },
  {
    "sheetRef": "Total!I9",
    "name": "فرش",
    "amountMinor": 6000000
  },
  {
    "sheetRef": "Total!I10",
    "name": "NOOR",
    "amountMinor": 0
  }
] as const

/**
 * `Data!D13` and `Data!D14` — balances the sheet stores that no formula
 * reads (D7). Zeros are listed too, so an empty section is unambiguous.
 */
export const GOLDEN_UNREACHABLE = [
  { sheetRef: 'Data!D13', name: 'ADIB C.C', storedMinor: 60000 },
  { sheetRef: 'Data!D14', name: 'HSBC C.C', storedMinor: 0 },
] as const
