import { writeFileSync } from 'node:fs'
import { DEFAULT_DUMP_PATH, Dump } from '../lib/import/dump'
import { toMinor, toMinorAtScale } from '../lib/money/round'

/**
 * `npm run goldens:generate` (T032).
 *
 * Reads every expected value named by `contracts/derivations.md` from the
 * dump's **`value`** fields, converts to minor units with half-up rounding,
 * and emits `tests/golden/expected.generated.ts`.
 *
 * **Goldens are generated, never hand-copied.** The first draft of the
 * derivations contract was built from the dump's `display` strings and was
 * wrong by 20-40 piastres on every non-zero installment figure — including a
 * "1 EGP rounding artifact" the contract then explained away, which was the
 * goldens' own error. A task that hand-copies expected values from a contract
 * table reintroduces exactly that class of mistake; a script that reads the
 * dump does not.
 *
 * The `SheetView` API this uses cannot return `display` at all (FR-046).
 */

const dump = Dump.fromFile(DEFAULT_DUMP_PATH)

const total = dump.sheet('Total')
const investment = dump.sheet('Investment')
const netWorthSheet = dump.sheet('Net Worth')
const installmentsSheet = dump.sheet('Installments')
const dashboard = dump.sheet('Dashboard')
const transactionsSheet = dump.sheet('Transactions')
const ratesSheet = dump.sheet('Rates')
const historySheet = dump.sheet('History')

const egp = (sheetName: string, a1: string): number => toMinor(sheetValue(sheetName, a1), 'EGP')

function sheetValue(sheetName: string, a1: string): number {
  const value = dump.sheet(sheetName).numberAt(a1)
  if (value === undefined) {
    throw new TypeError(`${sheetName}!${a1} holds no number in the dump`)
  }
  return value
}

const unpaidYears = Array.from({ length: 21 }, (_, i) => {
  const row = i + 2
  const year = Number(dashboard.stringAt(`H${row}`) ?? dashboard.numberAt(`H${row}`))
  return { year, amountMinor: egp('Dashboard', `I${row}`) }
})

const monthRows = []
for (let row = 2; row <= 25; row += 1) {
  const month = transactionsSheet.dateAt(`J${row}`, dump.sourceTimeZone)
  if (month === undefined) break
  const rate = transactionsSheet.valueAt(`N${row}`)
  monthRows.push({
    month,
    incomeMinor: egp('Transactions', `K${row}`),
    expenseMinor: egp('Transactions', `L${row}`),
    netMinor: egp('Transactions', `M${row}`),
    // The sheet's `IFERROR(..., "")` becomes null, never 0: a household that
    // earned nothing in a month did not save 0% of it.
    savingsRate: typeof rate === 'number' ? rate : null,
  })
}

const body = `/**
 * GENERATED by \`npm run goldens:generate\` — do not edit.
 *
 * Every value below was read from \`migration/sheet-dump.json\`'s \`value\`
 * field and converted to minor units by half-up rounding. Editing a number
 * here to make a test pass inverts the whole point of the file: the sheet is
 * the authority, and a failing golden means the port is wrong (FR-010).
 *
 * Source dump extracted at ${dump.extractedAt}.
 */

export const GOLDEN_TODAY = '2026-08-27'

/** \`Rates!B2:B4\`, at the scales R1 fixes per class. */
export const GOLDEN_RATES = {
  USD: { rateMinor: ${toMinorAtScale(sheetValue('Rates', 'B2'), 4)}, scale: 4, asOf: '${ratesSheet.dateAt('C2', dump.sourceTimeZone)}' },
  GOLD: { rateMinor: ${toMinorAtScale(sheetValue('Rates', 'B3'), 2)}, scale: 2, asOf: '${ratesSheet.dateAt('C3', dump.sourceTimeZone)}' },
  SILVER: { rateMinor: ${toMinorAtScale(sheetValue('Rates', 'B4'), 2)}, scale: 2, asOf: '${ratesSheet.dateAt('C4', dump.sourceTimeZone)}' },
} as const

/** \`Total!D2:L2\` — the non-investment partition. */
export const GOLDEN_TOTAL = {
  usdNative: ${toMinor(sheetValue('Total', 'D2'), 'USD')},
  usdEgp: ${egp('Total', 'E2')},
  goldNative: ${toMinor(sheetValue('Total', 'F2'), 'GOLD')},
  goldEgp: ${egp('Total', 'G2')},
  silverNative: ${toMinor(sheetValue('Total', 'H2'), 'SILVER')},
  silverEgp: ${egp('Total', 'I2')},
  egp: ${egp('Total', 'J2')},
  shortTermLiabilities: ${egp('Total', 'K2')},
  totalOfAll: ${egp('Total', 'L2')},
} as const

/** \`Investment!D2:K2\` — the investment partition. */
export const GOLDEN_INVESTMENT = {
  usdNative: ${toMinor(sheetValue('Investment', 'D2'), 'USD')},
  usdEgp: ${egp('Investment', 'E2')},
  goldNative: ${toMinor(sheetValue('Investment', 'F2'), 'GOLD')},
  silverNative: ${toMinor(sheetValue('Investment', 'G2'), 'SILVER')},
  goldEgp: ${egp('Investment', 'H2')},
  silverEgp: ${egp('Investment', 'I2')},
  egp: ${egp('Investment', 'J2')},
  investmentTotal: ${egp('Investment', 'K2')},
} as const

/** \`Net Worth!B12:B20\`. Both net-worth figures, neither unqualified (D4). */
export const GOLDEN_NET_WORTH = {
  totalAssets: ${egp('Net Worth', 'B12')},
  shortTermLiabilities: ${egp('Net Worth', 'B15')},
  remainingInstallments: ${egp('Net Worth', 'B16')},
  totalLiabilities: ${egp('Net Worth', 'B17')},
  includingInstallments: ${egp('Net Worth', 'B19')},
  excludingInstallments: ${egp('Net Worth', 'B20')},
  liquid: ${egp('Dashboard', 'B5')},
} as const

/** \`Installments!H2:H10\`, evaluated by the sheet at ${dump.extractedAt}. */
export const GOLDEN_INSTALLMENTS = {
  totalScheduled: ${egp('Installments', 'H2')},
  totalPaid: ${egp('Installments', 'H3')},
  totalRemaining: ${egp('Installments', 'H4')},
  nextDueOn: '${installmentsSheet.dateAt('H5', dump.sourceTimeZone)}',
  nextAmountDue: ${egp('Installments', 'H6')},
  due3m: ${egp('Installments', 'H7')},
  due6m: ${egp('Installments', 'H8')},
  due12m: ${egp('Installments', 'H9')},
  overdue: ${egp('Installments', 'H10')},
} as const

/** \`Dashboard!I2:I22\` — 21 calendar-year buckets. */
export const GOLDEN_UNPAID_BY_YEAR = ${JSON.stringify(unpaidYears, null, 2)} as const

/** \`Dashboard!F2:F6\` — the combined position per class. */
export const GOLDEN_ASSET_MIX = [
  { sheetRef: 'Dashboard!F2', label: 'EGP cash & accounts', egpMinor: ${egp('Dashboard', 'F2')} },
  { sheetRef: 'Dashboard!F3', label: 'USD (in EGP)', egpMinor: ${egp('Dashboard', 'F3')} },
  { sheetRef: 'Dashboard!F4', label: 'Gold (in EGP)', egpMinor: ${egp('Dashboard', 'F4')} },
  { sheetRef: 'Dashboard!F5', label: 'Silver (in EGP)', egpMinor: ${egp('Dashboard', 'F5')} },
  { sheetRef: 'Dashboard!F6', label: 'Property (paid to date)', egpMinor: ${egp('Dashboard', 'F6')} },
] as const

/** \`Transactions!G2\` — 100 USD on ${transactionsSheet.dateAt('A2', dump.sourceTimeZone)}. */
export const GOLDEN_TRANSACTION_EGP = ${egp('Transactions', 'G2')}

/** \`Transactions!J2:N25\` — the 24-month forward spine. */
export const GOLDEN_MONTHLY_ROLLUP = ${JSON.stringify(monthRows, null, 2)} as const

/** \`History!A4:G4\` — the sole genuine snapshot. Row 2 is a live mirror. */
export const GOLDEN_SNAPSHOT = {
  takenOn: '${historySheet.dateAt('A4', dump.sourceTimeZone)}',
  liquidMinor: ${egp('History', 'B4')},
  investmentsMinor: ${egp('History', 'C4')},
  propertyPaidMinor: ${egp('History', 'D4')},
  shortTermLiabilitiesMinor: ${egp('History', 'E4')},
  remainingInstallmentsMinor: ${egp('History', 'F4')},
  netWorthExclInstallmentsMinor: ${egp('History', 'G4')},
} as const

/** \`Total!I4:J10\` — hand-typed short-term liabilities, one of them Arabic. */
export const GOLDEN_LIABILITIES = ${JSON.stringify(
  Array.from({ length: 7 }, (_, i) => {
    const row = i + 4
    return {
      sheetRef: `Total!I${row}`,
      name: total.stringAt(`I${row}`),
      amountMinor: egp('Total', `J${row}`),
    }
  }),
  null,
  2,
)} as const

/**
 * \`Data!D13\` and \`Data!D14\` — balances the sheet stores that no formula
 * reads (D7). Zeros are listed too, so an empty section is unambiguous.
 */
export const GOLDEN_UNREACHABLE = [
  { sheetRef: 'Data!D13', name: '${dump.sheet('Data').stringAt('A13')}', storedMinor: ${egp('Data', 'D13')} },
  { sheetRef: 'Data!D14', name: '${dump.sheet('Data').stringAt('A14')}', storedMinor: ${egp('Data', 'D14')} },
] as const
`

writeFileSync('tests/golden/expected.generated.ts', body)
console.log(
  `Wrote tests/golden/expected.generated.ts from ${DEFAULT_DUMP_PATH} ` +
    `(extracted ${dump.extractedAt}); every value read from \`value\`, never \`display\`.`,
)

// Referenced so the linter sees these as used when the template changes.
void investment
void netWorthSheet
